### ISSUE TITLE
アプリケーションインポートが動作しない

### ISSUE THREAD

**Issue by kumamidori** [bearsunday/bearsunday.github.io#103]
## アプリケーション環境

- bear/sunday: "1.0.1"
  - ray/di: "2.2.2"

## 問題点

下記チュートリアルの「アプリケーションのインポート」セクションにて、

> 次にアプリケーションをインポートするためにsrc/Module/AppModule.phpでImportAppModuleを上書き(override)インストールします。

とあるが、この箇所が動作しない。

http://bearsunday.github.io/manuals/1.0/ja/tutorial.html

## 詳細

下記のとおり `Context` クラスがが使われているのだが、このクラスは実際には存在していない。

https://github.com/bearsunday/MyVendor.Weekday/blob/1.x/src/Module/AppModule.php#L16
`use BEAR\Package\Context;`
https://github.com/bearsunday/MyVendor.Weekday/blob/1.x/src/Module/AppModule.php#L48
`$this->override(new ImportAppModule($importConfig , Context::class));`

すみませんが、解決方法が分かりませんでした。ご確認頂ければと思います :tangerine:

**Comment by koriym** [comment]
`BEAR\Package\Context`はクラス名ではなくて、コンテキスト別のモジュールが入っているディレクトリ名です。prod-hal-appなら `BEAR\Package\Contex\ProdModule`や`BEAR\Package\Contex\HalModule`のクラス名を得るためのものです。

**Comment by koriym** [comment]
https://github.com/bearsunday/MyVendor.Weekday
このレポジトリと比べてみてください

**Comment by kumamidori** [comment]
上記リポジトリで、

https://github.com/bearsunday/MyVendor.Weekday/blob/1.x/src/Module/AppModule.php#L48
`$this->override(new ImportAppModule($importConfig , Context::class));`

とありますが、`Context `クラスは無いので、何らか書き換えが必要ですよね？

**Comment by kenjis** [comment]
> BEAR\Package\Contextはクラス名ではなくて、コンテキスト別のモジュールが入っているディレクトリ名

というのはちょっと意味がわからない説明です。ディレクトリ名なら `BEAR/Package/Context` だと思いますが。

**Comment by koriym** [comment]
> コンテキスト別のモジュールが入っているディレクトリ名

訂正します。ディレクトリ名ではなく正しくは名前空間です。（コードの表記と同じ）`BEAR\Package\Context`です。

**Comment by kumamidori** [comment]
https://github.com/bearsunday/MyVendor.Weekday
でアプリケーションインポートの動作を確認しました。
こちらのIssueはクローズして頂いてかまいません。

#### `Context::class` について

- プロジェクトセットアップ時に、PHPファイルとしてディレクトリ `vendor/bear/package/src/` 以下に「Context.php」があるわけではない（IDEの静的解析だと未解決になる）
- アプリケーション実行時には `BEAR\Package\Context` というクラスは存在している

**Comment by kenjis** [comment]
https://github.com/bearsunday/MyVendor.Weekday ですが、手許だと以下のエラーで全く動かないです。

~~~
$ php bootstrap/api.php get /import

Fatal error: Uncaught exception 'Ray\Di\Exception\Unbound' with message 'BEAR\AppMeta\AbstractAppMeta-'

  thrown in /home/vagrant/MyVendor.Weekday/vendor/ray/compiler/src/OnDemandCompiler.php on line 94
~~~

これは何のエラーでしょうか？

**Comment by kumamidori** [comment]
私の手元でも、チュートリアルどおりに作った方のプロジェクトで、kenjis さんが書かれたエラー↑と同じエラーになり、未解決です。（別途調べようと思っていました） :bow:

**Comment by kenjis** [comment]
Ray Compilerのエラーのようですが、エラーメッセージからは何なのかよくわからないです。
とくにソースのどこに問題があるのかの検討がつかないですね。
エラーメッセージが改善されるとうれしいですね。

**Comment by koriym** [comment]
エラー確認しました。

**Comment by koriym** [comment]
「`BEAR\AppMeta\AbstractAppMeta-`が束縛されていない」
エラーメッセージはクリアだと思いますがどうでしょうか。

`Unbound`は束縛が「ない」というエラーなのでエラー発生した側からソースの問題の箇所を示すのは難しいです。エラーメッセージの改善が難しいので、そのかわりその束縛の状態を表すような情報をログにすれば良いかと考えてます。

**Comment by koriym** [comment]
問題はフレームワークの問題なのか（この場合そうです）ユーザーの問題なのかが混ざって伝えられることだと思うのですが、これも簡単に解決出来る問題でもなくその出現機会を減らすぐらいしかないかと。

**Comment by koriym** [comment]
@kumamidori "アプリケーションインポートの動作を確認しました。"これはどの時点のものでしょうか？

**Comment by kumamidori** [comment]
get /import の動作確認ができたバージョンは、

masterブランチ
https://github.com/bearsunday/MyVendor.Weekday/commits/master
の、
`bdcd22a`
https://github.com/bearsunday/MyVendor.Weekday/commit/bdcd22a0721d79333ad2671e54eeb462c9bc0316
です。

（うっかりデフォルトブランチでない方＆やや古いのを見ていました :sweat: )

**Comment by koriym** [comment]
> やや古い

5ヶ月前のです！ 😳

**Comment by koriym** [comment]
しかしこちらも間違えがあって、確認したつもりだったのですが間違えがあったようです。

**Comment by koriym** [comment]
BEAR.Resource アップデートをして`AbstractAppMeta`束縛の問題は解決しました。

**Comment by kenjis** [comment]
https://github.com/bearsunday/MyVendor.Weekday ですが、

~~~
  - Removing cakephp/database (3.0.13)
  - Installing cakephp/database (3.1.0)
~~~

この影響で、以下のエラーがでるようになりました。

~~~
$ php bootstrap/api.php get /import

Fatal error: Interface 'Cake\Datasource\ConnectionInterface' not found in /home/vagrant/MyVendor.Weekday/vendor/cakephp/database/Connection.php on line 32
~~~

cakephp/database (3.0.13)に下げると、OKです。

~~~
$ php bootstrap/api.php get /import
200 OK
content-type: application/hal+json

{
    "blog": "Hello BEAR.Sunday",
    "_links": {
        "self": {
            "href": "/import"
        }
    }
}
~~~

cakephp/database のバグなんでしょうかね？

**Comment by kenjis** [comment]
一つ忘れてましたが、以下のファイル名の修正が必要です。Macなどではエラーになりませんが。

~~~
renamed:    src/Annotation/Benchmark.php -> src/Annotation/BenchMark.php
~~~

**Comment by koriym** [comment]
@kenjis `cakephp/database`のエラーでますね @kumamidori さんが分かると思うのですが
`src/Annotation/BenchMark.php`の件、PR出してもらっていいですか？

**Comment by kumamidori** [comment]
## `cakephp/database` のエラーについて

これは `cakephp/cakephp` 本体側で起きた問題が原因で、9/27に修正が masterマージされました。

https://github.com/cakephp/cakephp/pull/7459
https://github.com/cakephp/cakephp/blob/master/src/Database/composer.json#L13

ですが、今日（10/6）時点での最新である v3.1.0 は、9/20 にリリースされたバージョンなので、上記修正がまだパッケージ配布されていない状態です。

ref. http://cakephp.org/changelogs/3.1.0
https://packagist.org/packages/cakephp/cakephp

`cakephp/cakephp` 本体の修正版がリリースされたら解決となります。

**Comment by kenjis** [comment]
@koriym PRしときました。

**Comment by koriym** [comment]
@kenjis ありがとうございました。

**Comment by koriym** [comment]
@kumamidori 説明ありがとうございます。ではcakephp待ちで

**Comment by kenjis** [comment]
CakePHP 3.1.1リリースされてますね。
https://github.com/cakephp/cakephp/releases

**Comment by koriym** [comment]
テスト通るようになりました。
