### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by bakura10** [bearsunday/bearsunday.github.io#123]
In the first example in the tutorial:

```php
class Weekday extends ResourceObject
{
    public function onGet(int $year, int $month, int $day) : ResourceObject
    {
        $date = \DateTime::createFromFormat('Y-m-d', "$year-$month-$day");
        $this['weekday'] = $date->format('D');

        return $this;
    }
}
```
It's returning 400 if none of the parameters are set. Does changing the signature from int $day to int $day = 1 makes it optional by convention?

Should likely be specified here in the doc :)

**Comment by koriym** [comment]
I see. It might be good introduction how BEAR.Sunday set  `$_GET['day']` default value ? Instead of 

```php
$day = $_GET['year'] ?? 1;
$day = isset($_GET['year']) ? $_GET['year'] : 1; // php 5.x
```

**Comment by bakura10** [comment]
Actually I'd say that this "magic" stuff is quite complex to understand. Something like:

```php
public function onGet(Parameters $parameters) : ResourceObject
{
   $day = $parameters->get('day', 1); // 1 is default value
}
```

Seems like a better approach. Internally for our small app we've tried to completely remove all those magic and instead focused on explicit.

**Comment by koriym** [comment]
`$day = $parameters->get('day', 1); ` is imperative approach. It is impossible to provide "OPTIONS" method appeared later in tutorial. Also these "micro locator" pattern is needs more complexity for testing, I think.

**Comment by koriym** [comment]
BEAR.Sunday prefered more "declative" approach, You will see `@Embed` or `@ResourceParam` in same context. Feel too much magic ? Oh, Just carry on now, we can talk it later. ;)

**Comment by bakura10** [comment]
I'm just afraid that it makes it quite hard for use cases when you need to filter. I'm taking an example of an API that I'm using which has around 15 filters. Should we use it this way:

```php
public function onGet(array $ids, int $limit, int $page, int $sinceId, string $title, string $vendor, string $handle, string $productType, int $collectionId, $int createdAtMin, int $createdAtMax, int $updatedAtMin, int $updatedAtMax)
```

This can quickly go out of control and it's unclear how you can make one parameter optional or not.

**Comment by bakura10** [comment]
(sorry, I'm reading it page by page and commenting at the same time, I may find answer in the next pages actually ^^).

**Comment by koriym** [comment]
It's OK. I could know how people react in first glance.
Also you showed me good example. it might be ..

```php
    public function onGet(
        array $ids,
        int $limit,
        int $page,
        int $sinceId,
        string $title,
        string $vendor,
        string $handle,
        string $productType,
        int $collectionId = 1,
        int createdAtMin = 5, 
        int $createdAtMax = 5,
        int $updatedAtMin = 10,
        int $updatedAtMax = 10
    )
```
This declarative approach isn't clear which is optional or not ?

**Comment by bakura10** [comment]
It's pretty clear to me :). Then something like Assert (https://github.com/beberlei/assert) can be used to validate parameters. That's what we're doing here.

**Comment by koriym** [comment]
I see !

**Comment by koriym** [comment]
Using `@Valid` annotation to provide validation method is an answer for this.
http://bearsunday.github.io/manuals/1.0/en/validation.html

**Comment by koriym** [comment]
The purpose is for this is a separation of concern. I want to isolate validation method (or even class) and this can be changeable in context (in future)

**Comment by koriym** [comment]
An other idea is using `JSON Schema` for input validation. (`JSON Schema` is provided for only output  data now).  But anyway, my intention is separation of concern and more declarative approach for clarity and flexibility.

Just declare all parameters in method signature as preconditions, and devs need not worry this parameters validity. It should be all safe for use.

**Comment by bakura10** [comment]
I didn't reach this part yet (I have some work to finish but I'll be back to it throughout the week). I used to use things like input filters in the past to filter any input, but recently we've moved to a simplistic command handler system (https://github.com/zf-fr/zfr-command-bus) and we actually validate data in the domain, which is nice and explicit.

We often has middleware code like this:

```php
class CreateSms implements MiddlewareInterface
{
   private $commandBus;

   public function process(Request $request, Delegate $delegate): Response
   {
      $command = CreateSms::fromRequest($request->getParsedBody());
      $this->commandBus->dispatch($command);
   }
}
```

And the command itself is responsible to create the domain object:

```php
class CreateSms
{
   private $sms;

   public static function fromRequest(array $data): self
   {
      $self = new self();
      $self->sms = Sms::fromArray($data);
      return $self;
   }
}
```

And finally the domain do the validation:

```php
class Sms
{
    public static function fromArray(array $data): self
    {
       Assertion::keyExists($data['content']);
       $self = new self();
       $self->content = $data['content'];

       return $self;
    }
}
```

The nice thing of this approach is that the validation is done in context of the domain, and that you can actually reuse that in different context. For instance, let's say you wnat to create a SMS from a DB payload, you could add a simple static function that potentially do some transformation and then use the same "fromArray" function:

```php
class Sms
{
    public static function fromArray(array $data): self
    {
       Assertion::keyExists($data['content']);
       $self = new self();
       $self->content = $data['content'];

       return $self;
    }

    public static function fromDbPayload(array $data): self
    {
       // Let's say the column names are differnet, we can do a processing here:
       $data['content'] = $data['cnt'];
       return self::fromArray($data);
    }
}
```

We've experienced with a lot of things and having everything explicit, instead of relying on annotation (we do not have any annotation) has make our code suuuper explicit and easy to read and test :).

**Comment by koriym** [comment]
I understand and found a basic concept is fundamentally same. as "isolated reusable validation" component. (Current `@Valid` is not much same)

**Comment by koriym** [comment]
And about annotation, Sorry for it. I know some devs really hate it, but, just be patience in a while. Hope we can see some valid case later :)

**Comment by koriym** [comment]
@bakura10 Although maybe you forgotten this issue, JsonSchema input validation has implemented.

http://bearsunday.github.io/manuals/1.0/en/validation.html

**Comment by bakura10** [comment]
I'll have a look tomorrow. However you've made just a small typo (you've used shcema always of schema in the doc)

**Comment by koriym** [comment]
Fixed. Thanks !
