### ISSUE TITLE
リンク切れがあります

### ISSUE THREAD

**Issue by TakaakiFuruse** [bearsunday/bearsunday.github.io#176]
https://bearsunday.github.io/manuals/1.0/ja/tutorial.html#aop
の

>（メソッド実行オブジェクトMethodInvocation $invocationから元メソッドのオブジェクトとメソッドの名前を取得しています。）

の```MethodInvocation```にリンクされているURL http://www.bear-project.net/Ray.Aop/build/apigen/class-Ray.Aop.MethodInvocation.html がリンク切れ起こしています。

同様に

>次にベンチマークをしたいメソッドに目印をつけるためのアノテーションをsrc/Annotation/BenchMark.php に作成します。

の```アノテーション```にリンクされている http://www.bear-project.net/Ray.Aop/build/apigen/class-Ray.Aop.MethodInvocation.html もリンク切れを起こしています。

https://bearsunday.github.io/manuals/1.0/ja/tutorial.html
内のほかのリンクも踏んでみましたがリンク切れはこの2カ所だけのようでした。

ご対応ください。

**Comment by koriym** [comment]
issue作成ありがとうございました！
