### ISSUE TITLE
チュートリアル１のDIでエラーになる

### ISSUE THREAD

**Issue by OtomoHidehiko** [bearsunday/bearsunday.github.io#202]
https://bearsunday.github.io/manuals/1.0/ja/tutorial.html#di で
php bin/app.php get /weekday/2011/05/23 を実行するとエラーになる。

# 再現手順
composer install
php bin/app.php get /weekday/2011/05/23
# 実行
#2021-09-03 16:34:56 adachi@macbookpro.local:~/tmp/MyVendor.Weekday php8.0
! php bin/app.php get /weekday/2011/05/23

500 Internal Server Error
content-type: application/vnd.error+json

{
    "message": "Internal Server Error",
    "logref": "c201017d",
    "request": "get app://self/weekday?year=2011&month=05&day=23",
    "exceptions": "Ray\\Di\\Exception\\Unbound(dependency 'MyVendor\\Weekday\\MyLoggerInterface' with name '' used in /Users/adachi/tmp/MyVendor.Weekday/src/Resource/App/Weekday.php:14 ($logger))",
    "file": "/Users/adachi/tmp/MyVendor.Weekday/vendor/ray/di/src/di/Arguments.php(57)"
}

**Comment by KazuyaUchida** [comment]
var/tmp配下のファイルは `tmp/cli-hal-api-app/injector/MyVendor_Weekdaycli-hal-api-app/C/F/0wCShe7l9J3LAfJJ5rYg` 
のみ存在していました。

**500 Internal Sever Error 時のvar/tmp内のファイル** [0wCShe7l9J3LAfJJ5rYg.zip](https://github.com/bearsunday/bearsunday.github.io/files/7119852/0wCShe7l9J3LAfJJ5rYg.zip)

**200 OK 時のvar/tmp内のファイル** [0wCShe7l9J3LAfJJ5rYg.zip](https://github.com/bearsunday/bearsunday.github.io/files/7119863/0wCShe7l9J3LAfJJ5rYg.zip)

**Comment by yuki777** [comment]
Linked pull request : https://github.com/bearsunday/BEAR.Package/pull/380

**Comment by koriym** [comment]
@KazuyaUchida レポーとありがとうございます。対応、検討してます１

**Comment by koriym** [comment]
@KazuyaUchida @yuki777 今のチュートリアルでエラーにならない事を確認しました。
https://github.com/bearsunday/BEAR.Package/pull/380 で解決したのだと思います。
