### ISSUE TITLE
チュートリアルでPOSTリクエストを実行するとエラーが発生する

### ISSUE THREAD

**Issue by masakichi-eng** [bearsunday/bearsunday.github.io#251]
チュートリアルのDBにtodoを追加するPOSTリクエストを行うと下記のエラーが発生する。

` php bin/test.php get '/todos?id=1'`

```
PHP Fatal error:  Uncaught exception 'Ray\Compiler\Exception\Unbound' with message 'Psr\Cache\CacheItemPoolInterface-Ray\PsrCacheModule\Annotation\Shared'

  thrown in /{HOME}/MyVendor.Weekday/vendor/ray/compiler/src/CompileInjector.php on line 164

Fatal error: Uncaught exception 'Ray\Compiler\Exception\Unbound' with message 'Psr\Cache\CacheItemPoolInterface-Ray\PsrCacheModule\Annotation\Shared'

  thrown in /{HOME}/MyVendor.Weekday/vendor/ray/compiler/src/CompileInjector.php on line 164
```

**Comment by koriym** [comment]
まず`DateTimeImmutable`がUnboundのエラーが出ました。その他、要修正な箇所がありそうです。また、https://github.com/bearsunday/tutorial1 の方にもDBの文がコミットされてないのが判明しました。

**Comment by masakichi-eng** [comment]
@koriym 
ご確認いただきありがとうございます。
お手隙の際に修正とコミットしていただけましたら幸いです。

**Comment by koriym** [comment]
> チュートリアルのDBにtodoを追加するPOSTリクエストを行うと下記のエラーが発生する。
> php bin/test.php get '/todos?id=1'

これはgetですね？

**Comment by koriym** [comment]
https://github.com/bearsunday/tutorial1/commit/b49cdb5330f73ae2ac72b4b17b1f6a60c589cd04

このcommitを試していただけないでしょうか？

**Comment by masakichi-eng** [comment]
失礼しました。記載するコマンドを間違えており、実際に実行したのは下記のコマンドです。

` php bin/test.php post '/todos?todo=shopping'`

**Comment by masakichi-eng** [comment]
commitの内容を試してみましたが、変わらず同じエラーが発生してしまいました。

**Comment by koriym** [comment]
https://github.com/bearsunday/tutorial1/actions/runs/7564721564/job/20599304339
CI用意して確認できるようにしました。エラーは出ないようです。

比べるたり、下記のようにクリーンアップして再度試してもらえるでしょうか。

```
rm -rf *
git checkout .
composer install
```

**Comment by masakichi-eng** [comment]
ありがとうございます。
再度プロジェクトを作り直して最初からやり直した結果、エラーが発生せずに問題解決できました。

原因を探るためにエラーの出るプロジェクトの方で試行錯誤した結果、再度`composer install`を行うことで問題を解決できました。何かしらキャッシュ等が残っていたのかもしれません。

お付き合いいただきありがとうございました。

**Comment by koriym** [comment]
原因が分かりました。

## 原因

1. `DateTimeImmutable`が束縛されていないので、`MyVendor\Weekday\Resource\App\Todos`のクラスの依存解決ができず`Unbound`の例外になります。
2. この際に｀var/tmo/prod-cli-hal-api-app/di/compiled`ファイルが作られたまま終了します。
3. 前回、アルファベット順で`MyVendor\Weekday\Resource\App\Todos`まではコンパイルされていますが、それ以降はコンパイルされていません。
4. `Psr\Cache\CacheItemPoolInterface-Ray\PsrCacheModule\Annotation\Shared`の依存解決をするときに、``MyVendor\Weekday\Resource\App\Todos``以降になるのでコンパイルが必要です。しかしコンパイル中を示す`var/tmo/prod-cli-hal-api-app/di/compiled`があるために、下記のところでエラーになっています。

https://github.com/ray-di/Ray.Compiler/blob/cca1fefd755262db4b2fa673ae8847883a7b9a06/src/CompileInjector.php#L163

本来は`DateTimeImmutable`の依存解決ができないから発生したエラーですが、2回目以降のリクエストではファイルチェックのために`Psr\Cache\CacheItemPoolInterface-Ray\PsrCacheModule\Annotation\Shared`が束縛されていない（実際は束縛されていても）というエラーになってしまっています。

## 背景

`compiled`存在の理由

もし`compiled`ファイルがなければもう一度コンパイルが行われ、2回目も`Unbound（'DateTimeImmutable')`と正しいエラーが出ます。しかし、成功しないコンパイルが何度もプロダクション環境で行われることになります。それを避けるためのチェックファイルです。再度コンパイルを行うためには`tmp/`フォルダごと消去するのが確実です。

**Comment by koriym** [comment]
@masakichi-eng `'Psr\Cache\CacheItemPoolInterface-Ray\PsrCacheModule\Annotation\Shared'`の束縛に問題は無いのにエラーメッセージで誤った表記がされる問題は https://github.com/ray-di/Ray.Compiler/pull/110 で修正しました。この問題には気がついてなかったのですがこのissueを元に修正をすることができました。ありがとうございます。

**Comment by masakichi-eng** [comment]
@koriym 
詳細な原因調査と内容の共有、修正までしていただきありがとうございます。
改善に少しでも貢献できたようで何よりです。

**Comment by koriym** [comment]
> commitの内容を試してみましたが、変わらず同じエラーが発生してしまいました。
> 何かしらキャッシュ等が残っていたのかもしれません。

ここ少し解説します。（issueの整理のためにも）

`prod`環境ではコンパイルインジェクターというインジェクターが使われていて、ヘルスチェックの時に一度だけコンパイルして、その後はそのコンパイルで生成されたPHPがインジェクションを行います。

なので以降は束縛を変えても`var/tmp/di/`が変更されずエラーは変わりません。これは意図的な設計で、もし毎回コンパイルを許してしまうとリリース直後に複数のリクエストがそれぞれコンパイルをしてしまいCPUリソースが枯渇してしまいます。それを避けるための処理が不適切なエラーメッセージとなってユーザーにとても分かりにくいものになっていました。

他のプロジェクトではコンパイルしてからprodにするのでこの現象に遭いにくいという事情もありました。
